Fix ESP support in fstab & HVM integration

diff --git a/hooks/common/90-make-fstab b/hooks/common/90-make-fstab
--- a/hooks/common/90-make-fstab
+++ b/hooks/common/90-make-fstab
@@ -69,11 +69,33 @@ for part in `seq 1 ${NUMPARTITIONS}`; do
     esac
 
     if [ "${partdata2}" = "swap" ]; then
-        echo "UUID=$(blkid "$partdata7" -o value -s UUID) none swap sw 0 0" >> ${prefix}/etc/fstab
+        echo "UUID=$(blkid "$partdata6" -o value -s UUID) none swap sw 0 0" >> ${prefix}/etc/fstab
     else
-        echo "UUID=$(blkid "$partdata7" -o value -s UUID) ${partdata3} ${partdata2} ${partdata4} 0 1" >> ${prefix}/etc/fstab
+        if [ "${partdata2}" = "esp" ]; then
+            partdata2=vfat
+        fi
+        # ESP partitions are nested, so use the chrrot to pull out the UUID from the disk or partition
+        mount -o bind /proc ${prefix}/proc
+        mount -o bind /dev ${prefix}/dev
+        mount -o bind /dev/pts ${prefix}/dev/pts
+        mount -o bind /sys ${prefix}/sys
+        device="$(chroot ${prefix} findmnt -n -o SOURCE -M ${partdata3})"
+        uuid="$(chroot ${prefix} blkid "$device" -o value -s UUID)"
+        umount ${prefix}/sys
+        umount ${prefix}/dev/pts
+        umount ${prefix}/dev
+        umount ${prefix}/proc
+        if [ "x${uuid}" = "x" ]; then
+            logMessage "Could not find UUID for partition"
+            exit 1
+        fi
+        echo "UUID=${uuid} ${partdata3} ${partdata2} ${partdata4} 0 1" >> ${prefix}/etc/fstab
     fi
 done
+
+echo "Generated /etc/fstab:"
+cat ${prefix}/etc/fstab
+echo ""
 
 
 logMessage Checking for filesystem tools to install
